language: ruby
rvm:
- 2.1.0
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  matrix:
    secure: ls8tWnkyOeClXUvokV602+KXlzSVLz3SBd5SRp0r+CpOw0bAM0Ocgl6BVr0LIxs3wNtHlAMQhVKj/eddg4MyITf7Gozu54wI/vgXhXmdChHmjyLbwGUeLphdj/blvhgRNc2kr45+ET7nyOxmjusQhQA/Ux0Edv4vxLOK6t0WPkj7WAkXJpMWE/ntcHD0q/U69K3V+kOLI+uleHqPH6plhQl+wdxlxbqDhEWh/L/7fiNCw3Et3QWbKCQW2SzA/FS3+MTA+JxefWsCsTtUO52vMVXyxE/9pWFsEDoaPPaMKZJYOMzhyJ2R+v/QELSbZ0xFYHVjoSTK7eNTTqmwXbKVznxcxCGdN++w4+R0wo9YQQdfWIkjmUHeOHEDuDVykccD5BK3o+vE0R8adra+O1ihK944tmozvFDenAmEmucb+WQbtZTftk1mUVzX5a38IRtJjOClfQb4U34QwKIySMzokTj48HKpuApdQMrJnP3k/Rv7Nmws56gpjB1n/nJrDhj92DPdpADbyoxwj3W9XyWlowuripsnQxVz2EBaeno2XM7WRhu7UY/kQI4075ulM9Vee0CUYnL6FxYDLsWQDDth22op+bzz1d9G6ChjEkVeIfoTXd6b1M34kUDLvMvFDqUNnRdC7knO/7BjiNGNuceDLrNL4NsX2/ANBDILeWqw+6g=
