language: ruby
rvm:
- 2.1.0
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
env:
  matrix:
    secure: OlHGXyCdnZQIJvZUYsa9NZ8l+Af2xcXevEHgSew3sMdT/62ot6ftjDD0vFmJuIltQceqoh1BPYBi+oW4HY2p0SptwgwXP+QDJO4z6YTp3xpN/QlT6wfBYaotX4ub4Sew2TdEFrrN8oevFR4ZMWYqvGRAVOu+A9OX03qIkMBHbF7BI1XEfYk4wLxMOy7VDh814v7QAJIBhnp1hLcQR/2K7s7yrE4j40EBpCQkvgCfr+HGvnWdZ4YssIP0gP4oVneQ88RQjGdnrD+iP8u3krl2bdxarUqlwHvGgAkPxqL2Gy6HSdsbtBEBiaef0FTGYDYjD0cn2v2tJ3m5w266aiAHfzv0XKbQnS1iDbIjku2laJj6a76/jcy7wHUQySzFMbQ669kszTAneQBtmzSyGhdpvLOFPlBdaSnwSzxnvUYliYDWW9AbyacIxwatU8Fv48NSNenRZH3y89rKtYPsYbM/Z/SpJPoPoK2nhCmoMt2J73YjtHBwXpOb1NJdn5h4DJCsI4YEAYLh7u4C2DfIlJ+WTlMBXMx6Z6R/GQW0UkEWtZxf6v/rKLjh2bweCG7LQsbU9pzzwZ3MISW1lA4wL2Q3enF90AEU9EbiEGvcbIG+aJkzlYRGwPzUgof4Si75S7R2xBkDIfS18t76YLBrwx0DFGjOKvv5alViD99iQOz52PU=
