language: ruby
cache: bundler
rvm:
  - 2.4.1
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
  code_climate:
    repo_token: 47f64b6df0587c3466d6e852f74d84ec1107edd9d13a0f3f5045b27d117dc638
env:
  matrix:
    secure: HtRuSxmAzHb2MmBN36IB7JDIL0vCvD0NNDnv1Po7lH8IDjgjUkZXUegbxxrida+/7jlPRMJQzzF9mzciCpZnEuWhDVHaG/oYnFkIfb5ZmeTHj0Kl7w6gyiSmx3widmkUkrApF6sKGvBf3gtny4W/vhbl39+0YJ9STcw6BlhLMzzGWOZruKwhKDyWf6AcuOEz6wGcvK4aP6Rl54/4Z10xaG2aENg1BYJiBacXCMPdzw9Ayxy5/viTkAU6G2cztSBIlQ9QOWqIB4nr5El/oOyS65/Zsd11inzxyZeiR6x1tb0ia1XzTwQaBLGPtoNb+PaaaZl9eS+o0OTuJiVosRg5tB5pinddn8mcxLts49O3+bC5ghNzvAkJEjug2u2FjNtxNOEmLKCz8kBzZu/goBr7pjLn7LNP2fBDRcydCJNWDi2eeynP6McjRDwEyoyLtm1H4B42YilVy090KPwspQwGhw21Fy0Dmyex4Nxnh+qpBE4KY8bNiPLyWoTbNRdSSKGfSnVwgu6At6qDyP21uebqNdvytS+YGC7bMV8kRCt3PiXJ3Dcbt1rDFSi2Xn5Q6YGHyYw+ezrsKzN2WcW2BMw2aPR4qNOYaegFS9vuYAhbyI1MokvYTb30Z1RO5fejSTTZ6JjkFLVzzOq3spmEdI05SicsnVWIarYq6SPC/3BbvZ0=
