# System Prep
- hosts: all
  sudo: true
  pre_tasks:
    - apt: update_cache=yes
  roles:
    - role: rvm_io.rvm1-ruby
      tags: ruby
      sudo: True
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
      rvm1_user: '{{ ansible_ssh_user }}'
    - role: geerlingguy.git
    - role: zzet.postgresql
  tasks:
    - name: install js runtime
      apt: name=nodejs
    - name: install gem dependencies
      apt: pkg={{item}} state=installed
      with_items:
        - libcurl4-openssl-dev
        - imagemagick
        - libmagickwand-dev

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  tasks:
  - name: ensure database is created
    postgresql_db: name=development
  - name: ensure user has access to database
    postgresql_user: db=development name=vagrant priv=ALL

# Bundle install
- hosts: all
  tasks:
    - name: bundle install
      command: bash -lc "bundle install"
      args:
        chdir: /vagrant

- hosts: all
  tasks:
    - name: set working dir
      shell: 'echo "cd /{{ ansible_ssh_user }}" >> /home/{{ ansible_ssh_user }}/.bashrc'
