apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: serializer-budget
  labels:
    app: serializer
  namespace: serializer
spec:
  selector:
    matchLabels:
      app: serializer
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serializer
  labels:
    app: serializer
  namespace: serializer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: serializer
  template:
    metadata:
      labels:
        app: serializer
    spec:
      initContainers:
      - name: db-init
        image: postgres:latest
        command:
        - psql
        - postgres://root@cockroachdb-public:26257?sslmode=disable
        - "-c"
        - "create database if not exists postgres;"
      - name: rails-init
        image: charlieegan3/serializer:32fe8fbe522b5f9341ca34bb19e83993
        command:
        - rails
        - db:create
        - db:migrate
        - assets:precompile
        envFrom:
        - configMapRef:
            name: serializer-config
      containers:
      - name: web
        image: charlieegan3/serializer:32fe8fbe522b5f9341ca34bb19e83993
        envFrom:
        - configMapRef:
            name: serializer-config
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "100m"
