default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER", "postgresql") %>
  encoding: <%= ENV.fetch("DATABASE_ENCODING", "unicode") %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  url: <%= ENV.fetch("DATABASE_URL", "") %>
