production:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
