default: &default
  adapter: cockroachdb
  port: 26257
  host: cockroachdb
  user: root

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
